version: 3.8
services:
  movies:
    image: 15ume033/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: 15ume033/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: 15ume033/payrecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: 15ume033/paydth:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
    
